#!/usr/bin/env python3
"""Regenerate resources/settings/settings.xml (the Garmin Connect settings UI).

Four global settings plus 15 metric pickers -- one per slot of each layout
preset -- where every picker repeats the same metric list. Hand-editing 15
copies invites drift, so this script owns the file: edit the tables below,
re-run, commit the result. Deterministic; running it twice is a no-op.

Property ids and defaults live in resources/settings/properties.xml and
titles in resources/strings/strings.xml (both hand-written); this file only
wires property ids to title strings and repeats the metric list.
"""

import os

# Metric entries shared by every slot picker: (value, string id), in display
# order. Value 13 is historically unused and intentionally absent.
METRICS = [
    (0, "MetricOff"), (1, "MetricTimer"), (2, "MetricClock"),
    (3, "MetricDist"), (4, "MetricLDist"), (5, "MetricLTime"),
    (6, "MetricPace"), (7, "MetricLPace"), (8, "MetricCPace"),
    (9, "MetricSpeed"), (10, "MetricCSpd"), (11, "MetricHR"),
    (12, "MetricAHR"), (14, "MetricCad"), (15, "MetricACad"),
    (16, "MetricCal"), (17, "MetricAsc"), (18, "MetricAlt"),
]

# Slot pickers: (property id, title string id), in display order -- the
# shipped-default layout (4) first, then the rest by descending field count.
# Within a layout, the order matches Theme's slot indices (#49 spec).
SLOTS = [
    ("l4_n", "SettingL4N"), ("l4_e", "SettingL4E"),
    ("l4_s", "SettingL4S"), ("l4_w", "SettingL4W"),
    ("l5_c", "SettingL5C"), ("l5_tl", "SettingL5TL"),
    ("l5_tr", "SettingL5TR"), ("l5_bl", "SettingL5BL"),
    ("l5_br", "SettingL5BR"),
    ("l3_top", "SettingL3Top"), ("l3_mid", "SettingL3Mid"),
    ("l3_bot", "SettingL3Bot"),
    ("l2_top", "SettingL2Top"), ("l2_bot", "SettingL2Bot"),
    ("l1_c", "SettingL1C"),
]

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), os.pardir,
                   "resources", "settings", "settings.xml")


def list_setting(prop, title, entries):
    lines = ['        <setting propertyKey="@Properties.%s" title="@Strings.%s">'
             % (prop, title),
             '            <settingConfig type="list">']
    for value, sid in entries:
        lines.append('                <listEntry value="%d">@Strings.%s</listEntry>'
                     % (value, sid))
    lines.append('            </settingConfig>')
    lines.append('        </setting>')
    return lines


def toggle_setting(prop, title):
    return ['        <setting propertyKey="@Properties.%s" title="@Strings.%s">'
            % (prop, title),
            '            <settingConfig type="boolean" />',
            '        </setting>']


def main():
    lines = ['<resources>',
             '    <!-- Generated by tools/gen_settings.py; edit that script, not this file. -->',
             '    <settings>']
    lines += list_setting("theme", "SettingTheme",
                          [(0, "ThemeCockpit"), (1, "ThemeBridge"),
                           (2, "ThemeWall"), (3, "ThemePhosphor")])
    lines += list_setting("mode", "SettingMode",
                          [(0, "ModeDark"), (1, "ModeLight")])
    lines += list_setting("layout", "SettingLayout",
                          [(5, "Layout5"), (4, "Layout4"), (3, "Layout3"),
                           (2, "Layout2"), (1, "Layout1")])
    lines += toggle_setting("showLabels", "SettingLabels")
    for prop, title in SLOTS:
        lines += list_setting(prop, title, METRICS)
    lines += ['    </settings>', '</resources>', '']
    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    print("wrote " + os.path.normpath(OUT))


if __name__ == "__main__":
    main()
